services:
  web-app-php:
    build: .
    container_name: web-app-php-service
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: web-app-php-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27111:27017"
    volumes:
      - web-app-php-mongodb:/data/db

  postgresql:
    image: postgres:15
    container_name: web-app-php-postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5112:5432"
    volumes:
      - web-app-php-postgresql:/var/lib/postgresql/data

volumes:
  web-app-php-mongodb:
  web-app-php-postgresql:
